### ISSUE TITLE
Orange theme not there anymore

### ISSUE THREAD

**Issue by Tontonitch** [OutsideIT/FireMotD#126]
**Issue Type**

Bug report

**Issue Detail**

Orange theme not there anymore. 
Was there in 7.11.170608.
It's currently documented as existing.

* FireMotD version: 10.03.180725
* OS distribution: RHEL
* OS version: 7.5

**Expected Behavior**

Working Orange / orange theme

**Actual Behavior**

```
[root@xxxxxxxx ~]# /root/FireMotD -t orange
2018-08-29 12:04:45,901: FireMotD: Error: You specified a non-existant theme:
[root@xxxxxxxx  ~]# /root/FireMotD -t Orange
2018-08-29 12:04:51,848: FireMotD: Error: You specified a non-existant theme:
[root@xxxxxxxx  ~]#
```

**Comment by willemdh** [comment]
@Tontonitch Please try the latest version and use the install function. Orange theme should be working again. See https://github.com/OutsideIT/FireMotD/pull/131
