### ISSUE TITLE
after upgrade turn FireMotD slow on show up

### ISSUE THREAD

**Issue by hamwong** [OutsideIT/FireMotD#128]
**Issue Type**
Slow
Bug report / Enhancement Request

**Issue Detail**
After I get upgrade from V.7.05.170509 to v10.03.180725, after around 2-3sec loading, it's show up line by line, each line about 0.8-1.x sec, On previous version, after loading, info will show all info immediately
* FireMotD version: 10.03.180725
* OS distribution: Debian
* OS version: Linux 9 (stretch)

**Expected Behavior**
I expect same as previous, after loading will show all info at once

**Actual Behavior**
Info show up line by line

**How to reproduce Behavior**
I test on 3 Rpi, 2 Rpi 3 and 1 Rpi 3+, 1xRpi3 on Jessie and 1xRpi3+ on Stretch behavior same, line by line,
1xRpi3 on Jessie with old version V.7.05.17 function normal

I don't know is this is on Design, if it is, is there any options to behavior as previous version?

**Comment by willemdh** [comment]
@hamwong Hey, you are not the only one complainaing about slowness (https://github.com/OutsideIT/FireMotD/issues/125). On the 600 servers where I'm using it I don't experience a huge difference in speed. (I do notice the difference, but I found it neglectable)

I guess I should keep 1 hardcoded theme, which seems to be much faster on some platforms. I fear for now you better use and older version for now. I'm very busy atm and will be for the coming months. I hope to find some time in the Christmas holidays to improve the speed somehow.

**Comment by hamwong** [comment]
thanks and apperciated, I will try to fallback then. thanks.

**Comment by willemdh** [comment]
@hamwong Please also try multithreading with https://github.com/OutsideIT/FireMotD/releases/tag/v11.02.190106
For example:
`./FireMotD -T Eline -MT`

This is still an experimental feature though.

**Comment by willemdh** [comment]
Yeah the output is different. I will repopulate the themes with Nginx and Php in all themes. Also I think the `/usr/share/firemotd/cache` folder should be created with 777 permissions to be able to regenerate the cache files without sudo..

Could you try to:

```
chmod 777 /usr/share/firemotd/cache
FireMotD -G all -d
FireMotD -S -D all -d
```

And let me know if that improves your situation?

**Comment by hamwong** [comment]
yes, your command mostly work, error msg is gone, but only appear as below, info is gone
`###############################################################################
###############  OpenhabianPi-Server  #########################################
###############################################################################
###############################################################################
`
command run as below
`sudo FireMotD -S -D all -d
2019-01-13 02:57:32,271: FireMotD: Info: Debug mode
2019-01-13 02:57:32,286: FireMotD: Info: FireMotD action save started
2019-01-13 02:57:32,302: FireMotD: Info: Exportfile /usr/share/firemotd/data/FireMotD.json found.
2019-01-13 02:57:32,315: FireMotD: Info: Template type set to all. Overwriting..
2019-01-13 02:57:32,352: FireMotD: Info: Exploring Elasticsearch
2019-01-13 02:57:32,410: FireMotD: Info: Exploring HostIp
2019-01-13 02:57:32,472: FireMotD: Info: Exploring Httpd
2019-01-13 02:57:32,523: FireMotD: Info: Exploring InstallDate
2019-01-13 02:57:32,568: FireMotD: Info: Exploring Kernel
2019-01-13 02:57:32,612: FireMotD: Info: Exploring Kibana
2019-01-13 02:57:32,652: FireMotD: Info: Exploring Logstash
2019-01-13 02:57:32,692: FireMotD: Info: Exploring Mysql
2019-01-13 02:57:32,746: FireMotD: Info: Exploring Nginx
2019-01-13 02:57:32,809: FireMotD: Info: Exploring Php
2019-01-13 02:57:33,020: FireMotD: Info: Exploring Platform
2019-01-13 02:57:33,108: FireMotD: Info: Exploring Postgres
2019-01-13 02:57:33,153: FireMotD: Info: Exploring Release
2019-01-13 02:57:33,225: FireMotD: Info: Exploring Updates
2019-01-13 02:58:08,017: FireMotD: Info: Export system data to "/usr/share/firemotd/data/FireMotD.json" finished.
2019-01-13 02:58:08,030: FireMotD: Info: FireMotD action save finished
`

**Comment by hamwong** [comment]
Hi, here you go, really apperciated your fully help
```sudo ls -la
[sudo] password for openhabian:
total 72
drwxrwxrwx 2 root       root       4096 Jan 13 03:12 .
drwxr-xr-x 6 root       root       4096 Jan 12 06:01 ..
-rw-rw-rw- 1 openhabian openhabian 3635 Jan 13 03:12 firemotd-Blanco.motd
-rw-rw-rw- 1 openhabian openhabian 3598 Jan 13 02:27 firemotd-Blue.motd
-rw-rw-rw- 1 openhabian openhabian 4491 Jan 13 02:27 firemotd-Digipolis.motd
-rw-rw-rw- 1 openhabian openhabian 4493 Jan 13 02:27 firemotd-Elastic.motd
-rw-rw-rw- 1 openhabian openhabian 4493 Jan 13 02:27 firemotd-Eline.motd
-rw-rw-rw- 1 openhabian openhabian 4786 Jan 13 02:27 firemotd-Gray.motd
-rw-rw-rw- 1 openhabian openhabian 6701 Jan 13 03:09 firemotd-Modern.motd
-rw-rw-rw- 1 openhabian openhabian 4790 Jan 13 02:28 firemotd-Orange.motd
-rw-rw-rw- 1 openhabian openhabian 3598 Jan 13 02:28 firemotd-Red.motd
-rw-rw-rw- 1 openhabian openhabian 3598 Jan 13 02:28 firemotd-Zebra.motd```

**Comment by willemdh** [comment]
And the output of `FireMotD -R Elastic` and content of `/usr/share/firemotd/data/FireMotD.json`?

**Comment by hamwong** [comment]
Excellet, after run FireMotD -G Elastic -d, then FireMotD -t Elastic, it come out now
thanks for help me out, sir, sould you mind update your fix way at REAMD page so everyone ulse may have a look when facing issue, I won't mind do it for you.

Really thanks

**Comment by willemdh** [comment]
@hamwong 
Feel free to submit a pr to improve the docs. Glad it's working for you now. You can generate caches for all themes with:
`FireMotD -G all -d`

**Comment by willemdh** [comment]
Took some time to improve the readme a bit. Please check https://github.com/OutsideIT/FireMotD/releases/tag/v11.03.190127
