### ISSUE TITLE
Error while reading the PostgreSQL version

### ISSUE THREAD

**Issue by hoetzgit** [OutsideIT/FireMotD#134]
**Issue Type**

Bug report

**Issue Detail**

FireMotD: The wrong variable is saved at line 541.

* FireMotD version: 11.02.190106
* OS distribution: Raspbian GNU/Linux 9 (stretch)
* OS version:

**Expected Behavior**

Variable "$PostgresVersion" is saved.

**Actual Behavior**

Variable "$NginxVersion" is saved.

**How to reproduce Behavior**

sudo /usr/local/bin/FireMotD -S -v
cat /usr/share/firemotd/data/FireMotD.json

**Comment by willemdh** [comment]
Thanks for reporting @hoetzgit 

Should be fixed in https://github.com/OutsideIT/FireMotD/releases/tag/v11.03.190127
