### ISSUE TITLE
Session Counter not working on RPi

### ISSUE THREAD

**Issue by ThomDietrich** [OutsideIT/FireMotD#37]
This is related to the last two commits. I'm currently just seeing
```bash
Sessions = pi@
```

I'll provide a PR as soon as I found the time to look into this.

**Comment by willemdh** [comment]
We could do sth like:

```
SessionCount="$(who | cut -d' ' -f1,12 | tr ' ' @ | tr '\n' ',' | tr -d '()' | rev | cut -c 2- | rev)"
if ! ContainsValidIp $SessionCount ; then
    SessionCount="$(who | cut -d' ' -f1,13 | tr ' ' @ | tr '\n' ',' | tr -d '()' | rev | cut -c 2- | rev)"
fi
if ! ContainsValidIp $SessionCount ; then
    SessionCount="$(who | grep -c "$USER")"
fi
```

**Comment by willemdh** [comment]
Seems it doesn't work properly on Centos 6 too. Looking into it.

**Comment by willemdh** [comment]
Reverted this change for now, made a test function. This is getting more complicated then I thought. Although it is a nice to have it will have to wait for some other changes.

**Comment by ThomDietrich** [comment]
Tested and working on RPi. Issue can be closed if you are seeing good results on Centos ;)

**Comment by dimon222** [comment]
Is it resolved?

**Comment by willemdh** [comment]
Kept this open as i want to i.prive session info

**Comment by willemdh** [comment]
For me it works fine, so I'm closing this for now. If it gives issues for you, let me know and I'll reopen.
