### ISSUE TITLE
Update Option

### ISSUE THREAD

**Issue by willemdh** [OutsideIT/FireMotD#78]
I was thinking of adding an auto update option. Sth like

`sudo ./FireMotD --Update`

**Comment by ThomDietrich** [comment]
Could you elaborate on "auto update"?

**Comment by willemdh** [comment]
Well it needs to be triggered of course :) (by whatever automation tool / cronjob etc)

**Comment by ThomDietrich** [comment]
Ah... I see. Well I do this via git. Yes, not everyone uses the git way of setting FireMotD up.

How about a dedicated script to initially install and later update FireMotD? Would decouple the the installation from execution and would ease setup while at it.

The instructions for a new user would be:

> To install or upgrade FireMotD on your system execute:
> ```
> sh -c "$(curl -fsSL https://raw.githubusercontent.com/willemdh/FireMotD/master/install.sh)"
> ```

**Comment by willemdh** [comment]
Also good for me :) Do you have something that works already?

**Comment by ThomDietrich** [comment]
My process is based on git. I'd not recommended that for others as git is not installed by default...
Hence the answer is sadly no. Sorry

**Comment by willemdh** [comment]
ok i'll put it on my to do

**Comment by willemdh** [comment]
@ThomDietrich Check https://github.com/orgs/OutsideIT/teams/firemotd/discussions/4

Code should be added so the required packages are installed when apt-get is used too

**Comment by willemdh** [comment]
Added the required code for apt packages. Closing this issue, please use:

`curl -s https://raw.githubusercontent.com/OutsideIT/FireMotD/master/FireMotD -o ~/FireMotD && chmod 755 ~/FireMotD && sudo ~/FireMotD -I -d`
