### ISSUE TITLE
jq: command not found

### ISSUE THREAD

**Issue by kingy444** [OutsideIT/FireMotD#82]
**Issue Type**

Bug report

**Issue Detail**

* FireMotD version: FireMotD v8.09.171011
* Platform = Raspberry Pi 3 Model B Rev 1.2
* OS distribution: Raspbian GNU/Linux 8 (jessie)
* OS version: Linux 4.9.35-v7+

**Expected Behavior**
The current release is not working correctly on raspberry pi - i am running FireMotD 6.13.170302 on one pi successfully and 7.05.170509 on another. 
Neither successfully run v8

**Actual Behavior**
Return FireMotD results

**How to reproduce Behavior**
Install on Raspberry Pi

![firemotd](https://user-images.githubusercontent.com/7148670/33771566-82f619c2-dc85-11e7-819d-60c0f0f5877e.JPG)

**Comment by ThomDietrich** [comment]
Hello @kingy444,
the error says `jq` can not be found on your system. Why not simply install it 😄  https://github.com/OutsideIT/FireMotD/blob/master/readme.md#install-dependencies

**Comment by willemdh** [comment]
We should probably best check for it and suggest installation

**Comment by ThomDietrich** [comment]
My opinion would be the dedicated installation and update script mentioned in #78

**Comment by ThomDietrich** [comment]
Ah you mean to check prerequisites while starting FireMotD. Yes I agree. The same goes for the other tools used, potentially you should also check for a supported distribution (?) and for #77

**Comment by kingy444** [comment]
didnt even know what jq was sorry. didnt realise that their was new install requirements. ill try that when i get home thanks

**Comment by ThomDietrich** [comment]
this error message is always a bit misleading. Happened to us all ;)
You might be happy to hear that @willemdh already thought of a solution, see #83
